development:
  secret_key_base: fa3614d0736ce9d7633784ff5152bdc5d8b46b198e4b25de9a94e5bb6d0867c36a4e5f183a4303f8ab4005e8df98602db2d3249e72847f75ac835230cd546b69

test:
  secret_key_base: de27b4e671234d31fb46d62607df091a6e9569261e2ff1aff5ad53634e7a33d9a7e58504c521ca5f3b32f8eaffd05a49a4539d3f258ecb43af9cd505bddbbef9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

staging:
  secret_key_base: ENV['STAGE_SECRET_KEY_BASE']

production:
  secret_key_base: <%= ENV["PROD_SECRET_KEY_BASE"] %>
